task_2/askme_eremin/askme_eremin/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from app.views import login_view
from app.views import question_detail

urlpatterns = [
    path("", views.index, name="index"),
    path("hot/", views.hot, name="hot"),
    path("settings/", views.settings, name="settings"),
    path('login/', login_view, name='login'),
    path("signup/", views.signup, name="signup"),
    path("tag/", views.tag, name="tag"),
    path("ask/", views.ask, name="ask"),
    path('question/<int:question_id>/', views.question_detail, name='question'),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

task_2/askme_eremin/app/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    heading_question = models.CharField(max_length=255)
    question_text = models.TextField()
    # answer = models.ForeignKey('Answer', on_delete=models.SET_NULL, null=True, blank=True)
    likes_user = models.ManyToManyField(User, through='QuestionLike', related_name='liked_questions', blank=True) 

    def __str__(self):
        return self.heading_question

    def likes_count(self):
        return self.likes_user.count()



class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers', null=True, blank=True)
    answer_text = models.TextField()
    right = models.BooleanField()
    likes_user = models.ManyToManyField(User, through='AnswerLike', related_name='liked_answers', blank=True)

    def __str__(self):
        return self.answer_text[:50]

class Tag(models.Model):
    tag_name = models.CharField(max_length=100)

    def __str__(self):
        return self.tag_name

class QuestionTag(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['question', 'tag']

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

class QuestionLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'question'] 

class AnswerLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'answer'] 

task_2/askme_eremin/templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3" style="height: 80px;">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            
            <a class="navbar-brand" href="{% url 'index' %}">Почему онлайн</a>
    
            <form class="d-flex align-items-center" style="position: absolute; left: 50%; transform: translateX(-50%);">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" style="height: 40px; width: 200px;">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
    
            <div class="d-flex align-items-center">
                {% block login %}
                {% endblock %}
            </div>
        </div>
    </nav>
    
    <div class="row gap-3 w-100">
        <div class="col-7 ms-5">
            {% block heading_question %}
            {% endblock %}
            
            {% block content %}
            {% endblock %}
           
        </div>
        <div class="col-4">
            <div class="mb-5">
                <p class="fs-2">Популярные теги</p>
                <button type="button" class="btn btn-primary mb-1 ">Почему не работает код</button>
                <button type="button" class="btn btn-secondary mb-1">Как включить пк</button>
                <button type="button" class="btn btn-success mb-1">Что делаеть если...</button>
                <button type="button" class="btn btn-danger mb-1">Как кушать</button>
                <button type="button" class="btn btn-warning mb-1">Какие пары полезные?</button>
                <button type="button" class="btn btn-info mb-1">9 долгов, закроюсь?</button>
                <button type="button" class="btn btn-primary mb-1">Программисты</button>
            </div>
            <div class="mb-5">
                <p class="fs-2">Популярные спикеры</p>
                <div style="display: flex; flex-direction: column;">
                    <a href="#" class="mb-1 fs-5">Человек Человекович</a>
                    <a href="#" class="mb-1 fs-5">СММщица из вышки</a>
                </div>
            </div>
        </div>
    </div>

    
    {% block end %}
    {% endblock %}
    
      
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

task_2/askme_eremin/templates/layouts/pagination.html
<nav aria-label="Page navigation" class="ms-5">
    <ul class="pagination">
        {% if questions.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ questions.previous_page_number }}">Предыдущая</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Предыдущая</span>
            </li>
        {% endif %}
        {% if questions.number > 1 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ questions.number|add:"-1" }}">{{ questions.number|add:"-1" }}</a>
            </li>
        {% endif %}

        <li class="page-item active" aria-current="page">
            <span class="page-link">{{ questions.number }}</span>
        </li>

        {% if questions.number < questions.paginator.num_pages %}
            <li class="page-item">
                <a class="page-link" href="?page={{ questions.number|add:"1" }}">{{ questions.number|add:"1" }}</a>
            </li>
        {% endif %}

        {% if questions.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ questions.next_page_number }}">Следующая</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Следующая</span>
            </li>
        {% endif %}
    </ul>
</nav>

task_2/askme_eremin/templates/layouts/question.html
{% load static %}
<div class="row mb-3 w-100 bg-light p-3 d-flex card-body">
    <div class="col-2">
        <img src="{% static 'img/image.png' %}" alt="..." class="img-fluid img-thumbnail mb-2">
        <div class="d-flex flex-column">
            <input class="form-control mb-2" type="number" value="5" placeholder="Поле ввода по умолчанию" aria-label="пример ввода по умолчанию">
            <button class="btn btn-primary" type="submit">{{ question.likes_count }}</button>
        </div>
    </div>
    <div class="col-9 d-flex flex-column ms-1">
        <a href="{% url 'question' question_id=question.id %}" class="card-title mb-3">
            <h5>{{ question.heading_question  }}</h5>
        </a>
        <p class="card-text">{{ question.question_text  }}</p>
        <div class="row w-100 mt-auto">
            <div class="col-5">
                <a href="{% url 'question' question_id=question.id %}" class="card-link">Ответы</a>
            </div>
            <div class="col-5">
                <div>
                    <span>Тег: </span>
                    {% for question_tag in question.questiontag_set.all %}
                        <a href="{% url 'tag' %}?name={{ question_tag.tag.tag_name }}" class="card-link">{{ question_tag.tag.tag_name }}</a>{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>