task_2/askme_eremin/askme_eremin/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from app.views import login_view
from app.views import question_detail

urlpatterns = [
    path("", views.index, name="index"),
    path("hot/", views.hot, name="hot"),
    path("settings/", views.settings, name="settings"),
    path('login/', login_view, name='login'),
    path("signup/", views.signup, name="signup"),
    path("tag/", views.tag, name="tag"),
    path("ask/", views.ask, name="ask"),
    path('question/<int:question_id>/', views.question_detail, name='question'),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

task_2/askme_eremin/app/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    heading_question = models.CharField(max_length=255)
    question_text = models.TextField()
    # answer = models.ForeignKey('Answer', on_delete=models.SET_NULL, null=True, blank=True)
    likes_user = models.ManyToManyField(User, through='QuestionLike', related_name='liked_questions', blank=True) 

    def __str__(self):
        return self.heading_question

    def likes_count(self):
        return self.likes_user.count()



class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers', null=True, blank=True)
    answer_text = models.TextField()
    right = models.BooleanField()
    likes_user = models.ManyToManyField(User, through='AnswerLike', related_name='liked_answers', blank=True)

    def __str__(self):
        return self.answer_text[:50]

class Tag(models.Model):
    tag_name = models.CharField(max_length=100)

    def __str__(self):
        return self.tag_name

class QuestionTag(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['question', 'tag']

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

class QuestionLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'question'] 

class AnswerLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'answer'] 

task_2/askme_eremin/app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth import authenticate
from .models import Question, Answer
from django.shortcuts import redirect

class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Подтверждение пароля")
    avatar = forms.ImageField(required=False, label="Аватар")

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'password', 'confirm_password', 'avatar']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise ValidationError('Пароли не совпадают')
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)

        if not user.pk:
            user.save()

        profile, created = Profile.objects.get_or_create(user=user)

        if 'avatar' in self.cleaned_data:
            profile.avatar = self.cleaned_data['avatar']
            profile.save()

        if commit:
            user.save()

        return user

class CustomLoginForm(forms.Form):
    username = forms.CharField(label="Логин", max_length=150)
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("Неверный логин или пароль.")
            if not user.is_active:
                raise forms.ValidationError("Аккаунт отключен.")
        return cleaned_data


def add_answer(request, question_id):
    if request.method == 'POST':
        answer_text = request.POST.get('answer_text')
        if answer_text:
            question = Question.objects.get(pk=question_id)
            Answer.objects.create(
                user=request.user,
                answer_text=answer_text,
                right=False,
                question=question
            )
        return redirect('question', id=question_id)

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['answer_text', 'right']


class QuestionForm(forms.ModelForm):
    tags = forms.CharField(required=False, label="Теги", help_text="Введите теги через запятую")

    class Meta:
        model = Question
        fields = ['heading_question', 'question_text', 'tags']

    def clean_tags(self):
        tags_data = self.cleaned_data.get('tags')
        if tags_data:
            tags = [tag.strip() for tag in tags_data.split(',')]
            return tags
        return []

task_2/askme_eremin/templates/ask.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block login %}
    <div class="d-flex ms-2">
        <a href="{% url 'login' %}" class="card-link">Войти</a>
        <a href="{% url 'signup' %}"  class="card-link ms-4">Зарегистрироваться</a>
    </div>
{% endblock %}

{% block heading_question %}
    <div class="mb-5">
        <span class="fs-2">Новый вопрос</span>
    </div>
{% endblock %}

{% block content %}
    <!-- Сообщение об ошибке, если теги не указаны -->
    {% if form.non_field_errors %}
        <div class="mb-2">
            <span class="text-danger">{{ form.non_field_errors }}</span>
        </div>
    {% endif %}

    <!-- Форма для создания вопроса -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Заголовок вопроса -->
        <div class="row g-3 align-items-start mb-3">
            <div class="col-2">
                <label for="id_heading_question" class="col-form-label">Заголовок</label>
            </div>
            <div class="col-8">
                {{ form.heading_question }} <!-- Здесь используем поле из формы -->
            </div>
        </div>

        <!-- Текст вопроса -->
        <div class="row g-3 align-items-start mb-3">
            <div class="col-2">
                <label for="id_question_text" class="col-form-label">Текст вопроса</label>
            </div>
            <div class="col-8">
                {{ form.question_text }} <!-- Здесь используем поле из формы -->
            </div>
        </div>

        <!-- Теги -->
        <div class="row g-3 align-items-start mb-3">
            <div class="col-2">
                <label for="id_tags" class="col-form-label">Теги</label>
            </div>
            <div class="col-8">
                {{ form.tags }} <!-- Здесь используем поле для тегов из формы -->
            </div>
        </div>

        <!-- Кнопка отправки -->
        <div class="row g-3 align-items-start mb-3">
            <div class="col-2"></div>
            <div class="col-7">
                <button type="submit" class="btn btn-primary mb-1 ms-">Озадачиться</button>
            </div>
        </div>
    </form>
{% endblock %}

task_2/askme_eremin/templates/hot.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block login %}
    <img src="{% static 'img/image.png' %}" alt="Avatar" class="rounded-circle" style="width: 60px; height: 60px; margin-right: 10px;">
    <div class="d-flex flex-column ms-2">
        <p class="mb-1">Человек Человекович</p>  
        <a href="{% url 'settings' %}" class="card-link">Настройки</a>
        <a href="#" class="card-link">Выйти </a>
    </div>
{% endblock %}

{% block heading_question %}
    <div class="mb-3">      
        <span class="fs-2">Горячие вопросики</span>
        <a href="{% url 'index' %}" class="fs-4 ms-2">Новые вопросы</a>
    </div>
{% endblock %}

{% block content %}

    {% for question in questions %}

        {% include "layouts/question.html" %}
    {% endfor %}

{% endblock %}

{% block end %}
    {% include "layouts/pagination.html" %}
{% endblock %}

task_2/askme_eremin/templates/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block login %}
    {% if user.is_authenticated %}
        <img src="{% static 'img/image.png' %}" alt="Avatar" class="rounded-circle" style="width: 60px; height: 60px; margin-right: 10px;">
        <div class="d-flex flex-column ms-2">
            <p class="mb-1">{{ user.username }}</p>
            <a href="{% url 'settings' %}" class="card-link">Настройки</a>
            <a href="#" class="card-link" onclick="document.getElementById('logout-form').submit(); return false;">Выйти</a>
            <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                {% csrf_token %}
            </form>
        </div>
    {% else %}
        <div class="d-flex ms-2">
            <a href="{% url 'login' %}" class="card-link">Войти</a>
            <a href="{% url 'signup' %}" class="card-link ms-4">Зарегистрироваться</a>
        </div>
    {% endif %}
{% endblock %}

{% block heading_question %}
    <div class="mb-3">      
        <span class="fs-2">Новые вопросы</span>
        <a href="{% url 'hot' %}" class="fs-4 ms-2">Горячие вопросики</a>
    </div>
{% endblock %}

{% block content %}

    {% for question in questions %}

        {% include "layouts/question.html" %}

    {% endfor %}

{% endblock %}

{% block end %}
{% include "layouts/pagination.html" %}    
{% endblock %}

task_2/askme_eremin/templates/login.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <h1>Вход</h1>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Войти</button>
    </form>
    <p>Нет аккаунта? <a href="{% url 'signup' %}">Регистрация</a></p>
{% endblock %}

task_2/askme_eremin/templates/question.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block login %}
    <div class="d-flex ms-2">
        <a href="{% url 'login' %}" class="card-link">Войти</a>
        <a href="{% url 'signup' %}"  class="card-link ms-4">Зарегистрироваться</a>
    </div>
{% endblock %}

{% block heading_question %}
    <div class="mb-5">
        <span class="fs-2">Новый вопрос</span>
    </div>
{% endblock %}

{% block content %}
    <!-- Сообщение об ошибке, если теги не указаны -->
    {% if form.non_field_errors %}
        <div class="mb-2">
            <span class="text-danger">{{ form.non_field_errors }}</span>
        </div>
    {% endif %}

    <!-- Сообщение об ошибке тегов -->
    {% if errors %}
        <div class="mb-3">
            <ul class="text-danger">
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <!-- Форма для создания вопроса -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Заголовок вопроса -->
        <div class="row g-3 align-items-start mb-3">
            <div class="col-2">
                <label for="id_heading_question" class="col-form-label">Заголовок</label>
            </div>
            <div class="col-8">
                {{ form.heading_question }} <!-- Здесь используем поле из формы -->
                {% if form.heading_question.errors %}
                    <div class="text-danger">
                        {% for error in form.heading_question.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <!-- Текст вопроса -->
        <div class="row g-3 align-items-start mb-3">
            <div class="col-2">
                <label for="id_question_text" class="col-form-label">Текст вопроса</label>
            </div>
            <div class="col-8">
                {{ form.question_text }} <!-- Здесь используем поле из формы -->
                {% if form.question_text.errors %}
                    <div class="text-danger">
                        {% for error in form.question_text.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <!-- Теги -->
        <div class="row g-3 align-items-start mb-3">
            <div class="col-2">
                <label for="id_tags" class="col-form-label">Теги</label>
            </div>
            <div class="col-8">
                {{ form.tags }} <!-- Здесь используем поле для тегов из формы -->
                {% if form.tags.errors %}
                    <div class="text-danger">
                        {% for error in form.tags.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <!-- Кнопка отправки -->
        <div class="row g-3 align-items-start mb-3">
            <div class="col-2"></div>
            <div class="col-7">
                <button type="submit" class="btn btn-primary mb-1 ms-">Озадачиться</button>
            </div>
        </div>
    </form>
{% endblock %}

task_2/askme_eremin/templates/settings.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block login %}
    <img src="{% static 'img/image.png' %}" alt="Avatar" class="rounded-circle" style="width: 60px; height: 60px; margin-right: 10px;">
    <div class="d-flex flex-column ms-2">
        <p class="mb-1">Человек Человекович</p>  
        <a href="{% url 'settings' %}" class="card-link">Настройки</a>
        <a href="#" class="card-link">Выйти </a>
    </div>
{% endblock %}

{% block heading_question %}
    <div class="mb-5">
        <span class="fs-2">Настройки: </span>
        <span class="fs-2 ms-3">Человек Человекович</span>
    </div>
{% endblock %}

{% block content %}

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
        <label for="inputlogin" class="col-form-label">Логин</label>
        </div>
        <div class="col-5">
        <input type="login" id="inputlogin" class="form-control" title="Введите свой уникальный логин">
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
        <label for="inputmail" class="col-form-label">Эл. Почта</label>
        </div>
        <div class="col-5">
            <input type="mail" id="inputmail" class="form-control" title="Введите свою электронную почту">
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
        <label for="inputnick" class="col-form-label">Имя</label>
        </div>
        <div class="col-5">
        <input type="nick" id="inputnick" class="form-control" title="Введите своё имя которое будет отображаться на сайте">
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
        <label for="inputavatar" class="col-form-label">Аватар</label>
        </div>
        <div class="col-5">
            <img src="{% static 'img/image.png' %}" id="inputavatar" class="img-fluid w-50" alt="avatar image">
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
        
        </div>
        <div class="col-5">
            <div class="input-group">
                <input class="form-control" type="file" id="formFile" title="Нажмите, чтобы выбрать файл">
            </div>
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
        
        </div>
        <div class="col-5">
            <button class="btn btn-primary" type="submit">Сохранить</button>
        </div>
    </div>

{% endblock %}

task_2/askme_eremin/templates/signup.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block login %}
    <div class="d-flex ms-2">
        <a href="{% url 'login' %}" class="card-link">Войти</a>
        <a href="{% url 'signup' %}" class="card-link ms-4">Зарегистрироваться</a>
    </div>
{% endblock %}

{% block heading_question %}
  <div class="mb-5">
    <span class="fs-2">Регистрация: </span>
  </div>
{% endblock %}

{% block content %}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-2">
      <span class="text-danger">{{ form.non_field_errors }}</span>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
          <label for="{{ form.username.id_for_label }}" class="col-form-label">Логин</label>
        </div>
        <div class="col-5">
          {{ form.username }}
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
          <label for="{{ form.email.id_for_label }}" class="col-form-label">Эл. Почта</label>
        </div>
        <div class="col-5">
            {{ form.email }}
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
          <label for="{{ form.first_name.id_for_label }}" class="col-form-label">Имя</label>
        </div>
        <div class="col-5">
          {{ form.first_name }}
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
          <label for="{{ form.password.id_for_label }}" class="col-form-label">Пароль</label>
        </div>
        <div class="col-5">
          {{ form.password }}
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
          <label for="{{ form.confirm_password.id_for_label }}" class="col-form-label">Подтверждение</label>
        </div>
        <div class="col-5">
          {{ form.confirm_password }}
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2">
          <label for="{{ form.avatar.id_for_label }}" class="col-form-label">Аватар</label>
        </div>
        <div class="col-5">
          {{ form.avatar }}
        </div>
    </div>

    <div class="row g-3 align-items-start mb-3">
        <div class="col-2"></div>
        <div class="col-5">
            <button class="btn btn-primary" type="submit">Зарегистрироваться</button>
        </div>
    </div>

  </form>
{% endblock %}

task_2/askme_eremin/templates/tag.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block login %}
    {% if user.is_authenticated %}
        <img src="{% static 'img/image.png' %}" alt="Avatar" class="rounded-circle" style="width: 60px; height: 60px; margin-right: 10px;">
        <div class="d-flex flex-column ms-2">
            <p class="mb-1">{{ user.username }}</p>
            <a href="{% url 'settings' %}" class="card-link">Настройки</a>
            <a href="#" class="card-link" onclick="document.getElementById('logout-form').submit(); return false;">Выйти</a>
            <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                {% csrf_token %}
            </form>
        </div>
    {% else %}
        <div class="d-flex ms-2">
            <a href="{% url 'login' %}" class="card-link">Войти</a>
            <a href="{% url 'signup' %}" class="card-link ms-4">Зарегистрироваться</a>
        </div>
    {% endif %}
{% endblock %}

{% block heading_question %}
<div class="mb-3">
    <span class="fs-2">Тег:</span>
    <a href="{% url 'tag' %}?name={{ tag_name }}" class="fs-4 ms-2 text-primary">{{ tag_name }}</a>
</div>
{% endblock %}

{% block content %}
    {% if questions %}
        <div class="row">
            {% for question in questions %}
                <div class="col-12 mb-3">
                    {% include "layouts/question.html" %}
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-warning" role="alert">
            По тегу "{{ tag_name }}" не найдено вопросов.
        </div>
    {% endif %}
{% endblock %}

{% block end %}
    {% include "layouts/pagination.html" %}   
{% endblock %}